### ISSUE TITLE
Startup time getting slower and slower

### ISSUE THREAD

**Issue by ljgray** [chime-experiment/Daily_validation#13]
At the moment, the viewer queries data for _all_ available CSDs at startup, before displaying the first day. Each CSD gets its own database query, so that's ~1500 queries for rev_07 alone. Only the currently displayed day needs to have info available immediately, so this should be chaned

**Comment by ketiltrout** [comment]
I think probably what needs to happen is a XHR on CSD change (in, say, `set_csd`).

After the client JS decides it needs to change which CSD is being displayed, It would need to go something like this:

In `set_csd` main loop:
1.1. client disables all/most of the UI elements
1.2. `location.assign` for `new_csd`
1.3. XHR sent to server indicating that it wants to display CSD=`new_csd`
1.4. Set iframe src to rendered notebook for `new_csd`
1.5. Done

The server would respond with JSON containing:
2.1. new `csd_to_display` (which may _not_ be `new_csd`, because clients can't be trusted)
2.2. the targets of the six navigational buttons
2.3. the user's current opinion for `csd_to_display`
2.4. the opinion count for `csd_to_display`
2.5. probably the entirety of `csd_list`, since the server has it on hand and it may have changed 

Then, in the XHR callback, the client would finish up with:
3.1. If `csd_to_display != new_csd`:
  3.1.1. do another `location.assign`
  3.1.2. Set iframe src to rendered notebook for `csd_to_display`
3.2. Update script globals with data from server
3.3. Update and enable UI elements with data from globals

The templating itself wouldn't change much, except for not getting rid of the JSONified `opinions` list.

This trades login-in lag for csd-switching lag with the assumption that the second will be lower/less noticeable than the first.

We set the iframe src early, even though it may change later, to give the user something to distract themselves with while their client is waiting for the UI data.

If the XHR fails, then the user is going to be left with an almost entirely inactive UI.  Probably we'd keep the logout button enabled.  We could also maybe keep the CSD selection text box enabled.  The point of the `location.assign` in 1.2 is so they can do a hard-refresh in their browser to try to recover.

The `csd_list` from the server in 2.5 solves the problem of a logged-in user's session being currently unable to pick up new days when they arrive on bao.

This would also simplify the implementation of #12 since the user's chosen `N` could be sent in the XHR to the server to modify navigation.

**Comment by ketiltrout** [comment]
At the moment, this appears to be a client-side issue affecting only Safari.

I created a test-version of the viewer which tries to put as many opinions in the page sent to the client as possible (by ignoring the user field of the opinion) which make a ~500kB file that needs to be transferred on first log-in.

With Firefox, I see:
  - 1 second to get to the login redirect after sending credentials
  - 1.5 seconds of server wait while bao builds the page
  - 0.5 seconds to receive the 500kB file. (~1Mbps)
 
With Safari, I get:
  - 1 second to get to the login redirect after sending credentials
  - 1.5 seconds of server wait while bao builds the page
  - 14 seconds to receive the 500kB file. (~35kbps)

These numbers seem to agree with what @ljgray was seeing.

I don't see the same slowness in Safari when the server transfers the image blobs for the rendered notebooks which are of a similar size (~100kB) but take only ~25ms to transfer.   I want to play around a bit to see if I can figure out what Safari doesn't like about what the server is sending it.

**Comment by ketiltrout** [comment]
Tests on chrome and edge show equivalent results to the Firefox test above.

**Comment by ketiltrout** [comment]
A version of the viewer where I render all the javascript non-functional didn't seem to do anything, but making a static version of it (by just saving the HTML sent to my browser and then uploading it back to the server _does_ seem to work quickly, so I'm wondering now if it's a problem with the headers that the viewer is setting.

**Comment by ljgray** [comment]
Two other things to make note of:
- Disabling javascript in Safari doesn't help (consistent with the comment above)
- There's a 4-5 second gap with no network traffic between when the data is available and when the fetch query to get the notebook happens. In a safari private window, this gap is around 60 seconds (takes ~80 seconds for the page to display, although download time is the same)
